services:
    db:
        image: postgres:15
        container_name: 'postgres_db'
        environment:
            POSTGRES_DB: spenser
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: 1234
        ports:
            - 5432:5432

    app:
        build: .
        # image: spenser
        container_name: 'spenser'
        ports:
            - 3000:3000
        environment:
            NUXT_JWT_SECRET: changeme
            NUXT_DB_NAME: spenser
            NUXT_DB_HOST: db
            NUXT_DB_USER: admin
            NUXT_DB_PASSWORD: 1234
            NUXT_DB_PORT: 5432
        depends_on:
            - db
